openapi: 3.0.3
info:
  title: Swagger Nghich - OpenAPI 3.0
  description: |-
    API for Nghich Project
  version: 1.0.11

servers:
  - url: http://localhost:8080
tags:
  - name: users
    description: API cho Users
paths:
  /users/login:
    post:
      tags:
        - users
      summary: Logs user into the system
      operationId: login
      requestBody:
        description: The user that needs to be logged in
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginBody"
        required: true
      responses:
        "200":
          description: Login Successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Login Successfully
                  result:
                    $ref: "#/components/schemas/SuccessAuthentication"
        "422":
          description: Invalid input
  /users/register:
    post:
      tags:
        - users
      summary: Register user
      operationId: register
      requestBody:
        description: The user that needs to be registered
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterBody"
        required: true
      responses:
        "200":
          description: Register Successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Register Successfully
                  result:
                    $ref: "#/components/schemas/SuccessAuthentication"
        "422":
          description: Invalid input
  /users/logout:
    post:
      tags:
        - users
      summary: Logs out current logged in user session
      operationId: logout
      security:
        - BearerAuth: []
      requestBody:
        description: The user that needs to be logged out
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LogoutBody"
        required: true
      responses:
        "200":
          description: Logout Successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Logout Successfully
        "422":
          description: Invalid input
