openapi: 3.0.3
info:
  title: Swagger Nghich - OpenAPI 3.0
  description: |-
    API for Nghich Project
  version: 1.0.1

servers:
  - url: http://localhost:8080
tags:
  - name: users
    description: Operations about users
paths:
  /users/login:
    post:
      tags:
        - users
      summary: Logs user into the system
      operationId: login
      requestBody:
        description: The user that needs to be logged in
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginBody"
        required: true
      responses:
        "200":
          description: Login Successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Login Successfully
                  result:
                    $ref: "#/components/schemas/SuccessAuthentication"
        "422":
          description: Invalid input

components:
  schemas:
    LoginBody:
      type: object
      properties:
        email:
          type: string
          # example: user1@gmail.com
        password:
          type: string
          example: Password1.
    SuccessAuthentication:
      type: object
      properties:
        access_token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjYyMTE5MzczNjgxMjg2MjY0ZDhjNmJkIiwidG9rZW5fdHlwZSI6MCwiaWF0IjoxNzE1NjE4MzY2LCJleHAiOjE3MTU2MTkyNjZ9.HaYhDhj-aIzWMeEEf5p0piyYOE7WmVKlUxh2vq0sF9o
        refresh_token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjYyMTE5MzczNjgxMjg2MjY0ZDhjNmJkIiwidG9rZW5fdHlwZSI6MCwiaWF0IjoxNzE1NjE4MzY2LCJleHAiOjE3MTU2MTkyNjZ9.HaYhDhj-aIzWMeEEf5p0piyYOE7WmVKlUxh2vq0sF9o
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
