name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./be

    steps:
      - uses: actions/checkout@v4
      - name: "Create env file"
        run: echo "${{ secrets.ENV }}" > .env
      - name: Build the Docker image
        run: docker build --progress=plain -t sontt/nghich:v2 .
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Push the Docker image
        run: docker push sontt/nghich:v2
