name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./be

    steps:
      - uses: actions/checkout@v4
      - name: "Create env file"
        run: echo "${{ secrets.ENV }}" > .env
      - name: Build the Docker image
        run: docker build --progress=plain -t sontt382/nghichprj .
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Push the Docker image
        run: docker push sontt382/nghichprj
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull sontt382/nghichprj
            docker stop nghich
            docker rm nghich
            docker run -dp 4000:4000 --name nghich --restart unless-stopped sontt382/nghichprj
